// export const CLIENT_TO_SERVER = 'CLIENT_TO_SERVER'
const SERVER_TO_CLIENT_FAILURE = 'SERVER_TO_CLIENT_FAILURE'
const SERVER_TO_CLIENT_SUCCESS = 'SERVER_TO_CLIENT_SUCCESS'

module.exports = {
  SERVER_TO_CLIENT_FAILURE: SERVER_TO_CLIENT_FAILURE,
  SERVER_TO_CLIENT_SUCCESS: SERVER_TO_CLIENT_SUCCESS
}
