export const ENTER_QUESTION_ROOM_REQUEST = 'ENTER_QUESTION_ROOM_REQUEST'
export const ENTER_QUESTION_ROOM_SUCCESS = 'ENTER_QUESTION_ROOM_SUCCESS'
export const ENTER_QUESTION_ROOM_FAILED = 'ENTER_QUESTION_ROOM_FAILED'
